name: Build and Publish MCP Server

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build TypeScript
        run: npm run build
        
      - name: Run tests
        run: npm run test:ci
        
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## MCP Server Release ${{ github.ref }}
            
            ### Changes
            - Updated MCP server with latest features
            - Improved document parsing and search capabilities
            
            ### Installation
            ```bash
            npm install -g @nicepayments/developers-guide-mcp
            ```
            
            ### Usage
            Add to your Cursor MCP configuration:
            ```json
            {
              "mcpServers": {
                "developers-guide-mcp": {
                  "command": "npx",
                  "args": ["-y", "@nicepayments/developers-guide-mcp@latest"]
                }
              }
            }
            ```
          draft: false
          prerelease: false
